name: Build

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: |
          sudo apt install -y build-essential
          sudo apt install -y libsodium-dev
          make
